glimpse-editor/getglimpse-web

- config.toml
- content/about.md
- content/downloads.md
I'm leaving this pull request open so people can see the changes I'm making before I merge them. This is very much still a work in progress!
> Initial "About" page content

- content/about.md
It was suggested here that the original paragraph could be interpreted negatively and used against us later. I have expanded & elaborated on it to try and head of that criticism.
https://cybre.space/@grainloom/102424588367708547
> Updated based on feedback re: "wilful misinterpretations"

- content/about.md
- content/posts/a-hectic-first-week.md
- content/posts/updates-for-week-three.md
As this is longer than previous posts I've added sub-headings.
> Week 3 update and re-arranged FAQs

- content/_index.md
This adds a basic project description so people can see at a glance what the project is about.
> Added project description to the homepage

- content/about.md
Added entries for our decisions to use Github and Matrix as they pop up on social media and our own Github issues from time to time.
> Added two new entries to FAQs page

- content/about.md
These clarify that this fork is not a LibreOffice/OpenOffice type one, and also clarifies there's more to this project than *just* the name change.
> Added new FAQs

- content/posts/six-week-checkpoint.md
Hi, just fixed the typo in your vagrant based setup snippet.
> Fix typo in the vagrant up command

- layouts/partials/site-header.html
https://digital.globalclimatestrike.net/
We should show our support for the betterment of the climate by joining the digital climate strike.
This *will* make our website unavailable for today. but only today.
> Join the Digital Climate Strike

- layouts/partials/site-header.html
This reverts commit a3124e81c191a33dedcce3787874089ab446b684, reversing
changes made to ad856ea384391179f94b92e50313daf22cd84cfd.
> Revert "Merge pull request #45 from Member1221/master"

- content/_index.md
Open for review so people can change the subtitle to something more fitting.
Initial change is to change "is a fork of" to "is based on" according to suggestion from @meltheadorable
> Fixed initial phrasing

- .gitignore
This is typical of Hugo websites, and helps when deploying
them.
> Bundle Hugo theme

- content/about.md
- content/code-of-conduct.md
* Updated FAQs and code of conduct with chaomodus's new status as a governor
* Added two new questions to the FAQs
> End of jan post

- content/contribute.md
From getglimpse.app to glimpse-editor.org
> Update the wiki link

- content/about.md
- content/code-of-conduct.md
- content/downloads.md
- content/posts/glimpse-0-1-2-release-notes.md
> Release 0.1.2 draft changes

- content/about.md
- content/contribute.md
This PR re-jigs some of the questions in our FAQs page.
Removes old answers that no longer apply, rejigs the version scheme answer, and makes some minor tweaks upstream asked for.
Also adds new FAQ answer for people who keep asking us to make Glimpse look like Photoshop.
> Apply website fixes

- content/about.md
- content/downloads.md
- content/posts/a-month-of-many-patches.md
* Adds new blog post for latest progress
* Updates FAQ answers with suggestions from social media & feedback from upstream
* Updates Downloads page with new sources & support levels
> Mid april blog post (Work in Progress)

- content/about.md
- content/downloads.md
* Updates macOS support info
* Rewords a phrase upstream found upsetting
* Updates our upstream support FAQ
> Various FAQ page updates

- content/about.md
- content/posts/glimpse-0-2-0-on-schedule.md
* Makes statement about BLM and Pride Month
* Updates on Glimpse Image Editor 0.2.0 Progress
* Updates on server decommission and replace
* Confirms pre-emptive action on social media
Needs a review for tone and changes.
cc @BrainBlasted and @Member1221
> Draft blog post for early june

- .gitmodules
- config.toml
- content/about.md
- content/contribute.md
- content/downloads.md
- content/posts/an-exciting-second-year-ahead.md
Let me know what you think about future project direction, etc.
> Initial draft of new blog post for year 2 plans

- content/about.md
- Adds new FAQ answer for the cryptocurrency blockchain reward question
- Adds clarifying line in "How we govern ourselves" so people are clear we may end a debate if the only person interested in it (after a fair hearing) is the original person proposing the idea
> Added new FAQ for blockchain reward question
